Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = ["led.c"]

CPPPATH = [cwd]


if GetDepend("BSP_USING_KEY_LED"):
    src +=["key_led.c"]

group = DefineGroup('LED', src, depend = ['BSP_USING_LED'], CPPPATH = CPPPATH)

Return('group')