Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = ["LightSensor.c"]

CPPPATH = [cwd]


if GetDepend("BSP_USING_LightSensorDemo"):
    src +=["LightSensorDemo.c"]

group = DefineGroup('LightSensor', src, depend = ['BSP_USING_LightSensor'], CPPPATH = CPPPATH)

Return('group')